baseurl = "https://jsta.github.io/gh-cran-portfolio"
languageCode = "en-us"
title = "Github-CRAN Portfolio"
theme = "slate"
ignoreFiles = [ "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$",]
publishDir = "docs"

[params]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true

[[params.nav]]
name = "favorites"
tag = "favorite"
icon = "fas fa-star"

[[params.nav]]
name = "R"
tag = "rstats"
icon = "fab fa-r-project"

[[params.nav]]
name = "python"
tag = "python"
icon = "fab fa-python"

[[params.nav]]
name = "aws"
tag = "aws"
icon = "fab fa-aws"

[[params.nav]]
name = "TeX"
tag = "tex"
icon = "fas"
text = "TeX"

[[params.nav]]
name = "Fortran"
tag = "fortran"
icon = "fas"
text = "F"

[[params.nav]]
name = "C++"
tag = "cpp"
icon = "fas"
text = "C++"

[[params.nav]]
name = "Matlab"
tag = "matlab"
icon = "fas"
text = "M"
