baseurl = "https://jsta.github.io/ds-portfolio"
languageCode = "en-us"
title = "Data Science Portfolio"
theme = "slate"
ignoreFiles = [ "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$",]
publishDir = "docs"

[params]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true
[[params.nav]]
name = "favorites"
tag = "favorite"
icon = "rebel"

[[params.nav]]
name = "R"
tag = "R"
icon = "r-project"

[[params.nav]]
name = "python"
tag = "python"
icon = "python"

[[params.nav]]
name = "aws"
tag = "aws"
icon = "aws"

[[params.nav]]
name = "shopping"
tag = "shopping"
icon = "js"
